### ISSUE TITLE
Cull boats

### ISSUE THREAD

**Issue by WildWeazel** [Civcraft/MusterCull#26]
Add a method to remove empty boats in an area and/or clear them from the terminal

**Comment by BlackXnt** [comment]
https://github.com/Civcraft/MusterCull/pull/34

**Comment by ttk2** [comment]
cool, could we get automatic culling for large numbers?

**Comment by BlackXnt** [comment]
You have to be in-game to use it. Just stand near the area with all the boats and do /cull boat <range>. If you dont enter a range it is going to cull all the boats on the server(not that it will be so bad).

**Comment by BlackXnt** [comment]
I can prevent players from placing more boats if there are above x boats in the area. That will be good enough? it will only be a config change.

**Comment by ttk2** [comment]
that could work.

**Comment by BlackXnt** [comment]
I was wrong it will be more than a change to the config file. I will deal with it later today.

**Comment by jjj5311** [comment]
If player tries to place new boat just cull the boats that are unoccupied
in the range you would be checking?

**Comment by ttk2** [comment]
this is not urgent thanks though.

**Comment by ttk2** [comment]
really needed this command, got this stack 

2015-07-03 21:19:57 [INFO] ttk2 issued server command: /cull boat range 500
2015-07-03 21:19:57 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'cull' in plugin MusterCull v1.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.entity.EntityType.boat
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_45-internal]
        at org.bukkit.entity.EntityType.valueOf(EntityType.java:1) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at com.untamedears.mustercull.command.Commander.commandCull(Commander.java:632) ~[?:?]
        at com.untamedears.mustercull.command.Commander.onCommand(Commander.java:60) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        ... 15 more

**Comment by BlackXnt** [comment]
oops

You can do /cull BOAT 500 for now but I will make a pull with a fix.

**Comment by ttk2** [comment]
oh, that was it? thanks, I will get the boats in a bit.

**Comment by Maxopoly** [comment]
Added by https://github.com/Civcraft/MusterCull/pull/34
